version: "3.8"

services:
  todokodb:
    image: mysql:latest
    container_name: todo-kotlin-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-todoko-data:/var/lib/mysql
    networks:
      - todo-kotlin-server

volumes:
  mysql-todoko-data:

networks:
  todo-kotlin-server:
    driver: bridge